# Generated by Django 2.1.7 on 2019-03-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', '男'), ('Female', '女')], default='female', max_length=7),
        ),
    ]
