# Generated by Django 2.1.7 on 2019-03-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190321_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
