# Generated by Django 2.1.7 on 2019-04-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190410_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='激活状态'),
        ),
    ]
